### ISSUE TITLE
Issue building kibana

### ISSUE THREAD

**Issue by valleen** [SharpSeeEr/Dockerfiles#1]
Hi,

I have an error building the kibana image, can you help?

I just changed the node.js url to go to STEP 5 successfully....

`FROM microsoft/windowsservercore
# Build variable to allow passing in a specific version of Elasticsearch to download
ARG KIBANA_VERSION=6.3.0
ARG NODE_VERSION=10.4.1

# Download and extract 64-bit Node.js 
ADD ["https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-win-x64.zip", "/"]

RUN powershell.exe -Command \
  $zipPath = 'node-v' + $Env:NODE_VERSION + '-win-x64.zip' ; \
  Expand-Archive -Path $zipPath -DestinationPath \ ; \
  Remove-Item -Path $zipPath; \
  Rename-Item -Path $fullversion -NewName kibana;`

and here I have this error message:

> Rename-Item : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:157
 ...  ; Remove-Item -Path $zipPath; Rename-Item -Path $fullversion -NewNam ...
                                                      ~~~~~~~~~~~~
     CategoryInfo          : InvalidData: (:) [Rename-Item], ParameterBinding
   ValidationException
     FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M
   icrosoft.PowerShell.Commands.RenameItemCommand

**Comment by SharpSeeEr** [comment]
This does not surprise me.  :) I'll look into it today.

**Comment by SharpSeeEr** [comment]
Yeah, the Kibana Dockerfile was just all kinds of screwed up.  Looks like I committed in the middle of making changes or something.  I have fixed it and pushed the changes in this [commit](https://github.com/SharpSeeEr/Dockerfiles/commit/12e1f0c0bb5f9c93149440931cd0f09999b09339)
