### ISSUE TITLE
Installing ingest-attachment plugin on elasticsearch

### ISSUE THREAD

**Issue by valleen** [SharpSeeEr/Dockerfiles#2]
Sorry to bother you.
Do you have any idea how to install the ingest-attachment plugin?
I tried to 'docker exec -it cmd' and went to bin folder to execute 'elasticsearch-plugin install ingest-attachment' cmd but I have an error:

> Error occurred during initialization of VM
Could not reserve enough space for object heap

**Comment by SharpSeeEr** [comment]
The error message you are getting is coming from the Java runtime.  By default the `elasticsearch-plugin` command is trying to initialize java with memory parameters that exceed the amount of memory allocated to the container.  

You set the ES_JAVA_OPTS environment variable to overcome this, In the elasticsearch Dockerfile I set it to `-Xms512m -Xmx512m` using the `ENV` command.  This doesn't set it globally, so you have to set it again for your cmd session.

**Comment by valleen** [comment]
Hi, thanks for your answer.
I understood it is because the elasticsearch was running and it was not possible to install the plugin at that time. So, I ended up installing it on the image build, in the docker file:

`RUN .\elasticsearch-6.3.2\bin\elasticsearch-plugin install ingest-attachment --batch
`

right after

`ADD ["https://artifacts.elastic.co/downloads/elasticsearch/${ELASTICSEARCH_SOURCE}.zip", "/"]
RUN Expand-Archive -Path \$($Env:ELASTICSEARCH_SOURCE).zip -DestinationPath \ ; \
    Remove-Item -Path \$($Env:ELASTICSEARCH_SOURCE).zip ;
`

**Comment by SharpSeeEr** [comment]
Perfect.  Glad you got it figured out.  That's good to know for when I need to install a plugin in the future.
