### ISSUE TITLE
Containers running but calls fail

### ISSUE THREAD

**Issue by stephen-ciandt** [SharpSeeEr/Dockerfiles#3]
Hello,

I am trying to use your solution and have the containers up and running after having created the images.
Having downloaded the Java image into the "sources" folder, I ran these commands in the Elasticsearch and Kibana folders.

docker build -t elasticsearch:latest .
docker build -t kibana:latest .

They built fine.
I then kicked off the containers:

docker run -dt -p 9200:9200 -p 9300:9300 --name elasticsearch elasticsearch:latest
docker run -dt -p 5601:5601 --link elasticsearch --name kibana kibana:latest

The containers are up and running, but I am not able to get Elasticsearch to respond in the browser...

I am trying to call the Elasticsearch container using either localhost (as it runs on port 9200) or the what I can see Kibana calls (from the kibana.yml file).

http://localhost:9200/
or
http://elasticsearch:9200/

However, neither work... I am completely new to this so maybe the URL is wrong or something.
I really want to use this as it is an elegant solution - if you could help, it would be appreciated.

Thank you

**Comment by stephen-ciandt** [comment]
Okay, I found the issue - I had previously deleted the NAT network and had created a custom one so that I could specify a fixed IP range and addresses when running a group of containers using docker-compose.
Having reset Docker it now works as expected.

**Comment by SharpSeeEr** [comment]
Glad it was an "easy" fix.  And my apologies for not seeing this sooner.  Github didn't show any notifications.
