### ISSUE TITLE
Failed to obtain node locks

### ISSUE THREAD

**Issue by alex-prog96** [SharpSeeEr/Dockerfiles#5]
Hello, 

First of all thanks for creating and sharing these images. Huge help. However, I'm having trouble running the ElasticSearch image.

I've copied over the entire configuration. But when running the ElasticSearch container (on my server 2016 host) I'm getting the following Java error:

`[2018-09-25T15:11:13,156][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[G:\data\docker-cluster]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?`
...... (more of the stack trace)

Things I've tried:

- Removing the path.logs and path.data options in the elasticsearch.yml file, this solved the issue;
- Granting Full Access permissions on the G:\ drive and folders; got the same issue;
- Increasing the node.max_local_storage_nodes number to 10, same issue.

So, seeing as the default paths for the logs and data seem to work fine, it probably has something to with Windows permissions. Did you run into this issue during your testing?

Any help would be appreciated, thank you.

Java version: jdk1.8.0_181
Elasticsearch version: 6.4.1

**Comment by SharpSeeEr** [comment]
The dockerfile maps the G: drive to C:\data.  Which admittedly is probably not the best place, but the VM I use only gets a C: drive.

- Does C:\data exist on the server, outside of the container?
- Are the permissions on that folder set properly?

**Comment by alex-prog96** [comment]
The C:\data folder does exist and the permissions are set to allow all.

I've just tried running the image on a Windows 10 Pro host, and they work fine on there. Probably had something to do with my Server 2016 installation then.

Thanks for your help.
